version: '3.8'

volumes:
  gopher-shared:
    driver: local
    driver_opts:
      type: none
      device: ${BASE_DIR}/gopher
      o: bind

services:
  id26:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/argoproj/argo-workflows"
        VUL_TAG: "v3.0.10"
        GO_VERSION: "1.19"
    container_name: argo-workflows-26
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/argo-workflows-26:/analysis/repo/scan_results"

  id27:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/argoproj/argo-workflows"
        VUL_TAG: "v3.0.8"
        GO_VERSION: 1.19
    container_name: argo-workflows-27
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/argo-workflows-27:/analysis/repo/scan_results"

  id39:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/argoproj/argo-cd"
        VUL_TAG: "v2.4.0"
        GO_VERSION: 1.18
    container_name: argo-cd-39
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/argo-cd-39:/analysis/repo/scan_results"

  id63:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/aws/aws-sdk-go"
        VUL_TAG: "v1.32.13"
        GO_VERSION: "1.11"
    container_name: aws-sdk-go-63
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/aws-sdk-go-63:/analysis/repo/scan_results"

  id65:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/aws/aws-sdk-go"
        VUL_TAG: "v1.34.1"
        GO_VERSION: "1.11"
    container_name: aws-sdk-go-65
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/aws-sdk-go-65:/analysis/repo/scan_results"

  id66:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/aws/aws-sdk-go"
        VUL_TAG: "v1.34.1"
        GO_VERSION: "1.11"
    container_name: aws-sdk-go-66
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/aws-sdk-go-66:/analysis/repo/scan_results"

  id202:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/dedis/kyber"
        VUL_TAG: "v3.0.12"
        GO_VERSION: "1.13"
    container_name: dedis-kyber-202
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/dedis-kyber-202:/analysis/repo/scan_results"


  id204:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/dexidp/dex"
        VUL_TAG: "v2.26.0"
        GO_VERSION: "1.15"
    container_name: dexidp-dex-204
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/dexidp-dex-204:/analysis/repo/scan_results"

  id241:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/filecoin-project/lotus"
        VUL_TAG: "v1.4.2"
        GO_VERSION: "1.15"
    container_name: filecoin-project-lotus-241
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/filecoin-project-lotus-241:/analysis/repo/scan_results"

  id264:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/foxcpp/maddy"
        VUL_TAG: "v0.5.3"
        GO_VERSION: "1.15"
    container_name: foxcpp-maddy-264
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/results/known-vuls/foxcpp-maddy-264:/analysis/repo/scan_results"

  # id356:
  #   build:
  #     context: .
  #     args:
  #       REPO_URL: "https://github.com/gopasspw/gopass"
  #       VUL_TAG: ""
  #       GO_VERSION: ""
  #   container_name: gopasspw-gopass-356
  #   volumes:
  #     - "${BASE_DIR}/gopher/gopher:/analysis/gopher"
  #     - "${BASE_DIR}/results/known-vuls/gopasspw-gopass-356:/analysis/repo/scan_results"

