version: '3.8'

services:
  id65-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/aws/aws-sdk-go"
        VUL_TAG: "v1.34.1"
        GO_VERSION: "1.11"
    container_name: github.com-aws-aws-sdk-go-65-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-aws-aws-sdk-go-65-1:/analysis/repo/scan_results"
  id66-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/aws/aws-sdk-go"
        VUL_TAG: "v1.34.1"
        GO_VERSION: "1.11"
    container_name: github.com-aws-aws-sdk-go-66-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-aws-aws-sdk-go-66-1:/analysis/repo/scan_results"
  id204-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/dexidp/dex"
        VUL_TAG: "v2.26.0"
        GO_VERSION: "1.15"
    container_name: github.com-dexidp-dex-204-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-dexidp-dex-204-1:/analysis/repo/scan_results"
  id241-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/filecoin-project/lotus"
        VUL_TAG: "v1.4.2-rc1"
        GO_VERSION: "1.15"
    container_name: github.com-filecoin-project-lotus-241-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-filecoin-project-lotus-241-1:/analysis/repo/scan_results"
  id356-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/gopasspw/gopass"
        VUL_TAG: "v1.10.1"
        GO_VERSION: "1.12"
    container_name: github.com-gopasspw-gopass-356-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-gopasspw-gopass-356-1:/analysis/repo/scan_results"
  id593-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/edgexfoundry/app-functions-sdk-go"
        VUL_TAG: "v2.0.1"
        GO_VERSION: "1.16"
    container_name: github.com-edgexfoundry-app-functions-sdk-go-593-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-edgexfoundry-app-functions-sdk-go-593-2:/analysis/repo/scan_results"
  id593-3:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/edgexfoundry/app-functions-sdk-go"
        VUL_TAG: "v2.0.1"
        GO_VERSION: "1.16"
    container_name: github.com-edgexfoundry-app-functions-sdk-go-593-3
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-edgexfoundry-app-functions-sdk-go-593-3:/analysis/repo/scan_results"
  id618-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/kiali/kiali"
        VUL_TAG: "v1.15.2"
        GO_VERSION: "1.11"
    container_name: github.com-kiali-kiali-618-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-kiali-kiali-618-1:/analysis/repo/scan_results"
  id618-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/kiali/kiali"
        VUL_TAG: "v1.15.2"
        GO_VERSION: "1.11"
    container_name: github.com-kiali-kiali-618-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-kiali-kiali-618-2:/analysis/repo/scan_results"
  id830-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/tendermint/tendermint"
        VUL_TAG: "v0.34.8"
        GO_VERSION: "1.15"
    container_name: github.com-tendermint-tendermint-830-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-tendermint-tendermint-830-1:/analysis/repo/scan_results"
  id830-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/tendermint/tendermint"
        VUL_TAG: "v0.34.8"
        GO_VERSION: "1.15"
    container_name: github.com-tendermint-tendermint-830-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-tendermint-tendermint-830-2:/analysis/repo/scan_results"
  id870-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/weaveworks/weave-gitops"
        VUL_TAG: "v0.11.0-rc.1"
        GO_VERSION: "1.18"
    container_name: github.com-weaveworks-weave-gitops-870-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-weaveworks-weave-gitops-870-1:/analysis/repo/scan_results"
  id870-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/weaveworks/weave-gitops"
        VUL_TAG: "v0.11.0-rc.1"
        GO_VERSION: "1.18"
    container_name: github.com-weaveworks-weave-gitops-870-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-weaveworks-weave-gitops-870-2:/analysis/repo/scan_results"
  id870-3:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/weaveworks/weave-gitops"
        VUL_TAG: "v0.11.0-rc.1"
        GO_VERSION: "1.18"
    container_name: github.com-weaveworks-weave-gitops-870-3
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-weaveworks-weave-gitops-870-3:/analysis/repo/scan_results"
  id870-4:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/weaveworks/weave-gitops"
        VUL_TAG: "v0.11.0-rc.1"
        GO_VERSION: "1.18"
    container_name: github.com-weaveworks-weave-gitops-870-4
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-weaveworks-weave-gitops-870-4:/analysis/repo/scan_results"
  id980-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/docker/docker"
        VUL_TAG: "v28.0.1"
        GO_VERSION: "1.11"
    container_name: github.com-docker-docker-980-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-docker-docker-980-1:/analysis/repo/scan_results"
  id994-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/moby/moby"
        VUL_TAG: "v28.0.1"
        GO_VERSION: "1.11"
    container_name: github.com-moby-moby-994-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-moby-moby-994-1:/analysis/repo/scan_results"
  id1023-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/px-org/PanIndex"
        VUL_TAG: "v3.1.2"
        GO_VERSION: "1.19"
    container_name: github.com-px-org-PanIndex-1023-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-px-org-PanIndex-1023-1:/analysis/repo/scan_results"
  id1207-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/sylabs/sif"
        VUL_TAG: "v2.8.0"
        GO_VERSION: "1.18"
    container_name: github.com-sylabs-sif-1207-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-sylabs-sif-1207-1:/analysis/repo/scan_results"
  id1222-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/sigstore/cosign"
        VUL_TAG: "v1.11.1"
        GO_VERSION: "1.18"
    container_name: github.com-sigstore-cosign-1222-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-sigstore-cosign-1222-1:/analysis/repo/scan_results"
  id1226-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/matrix-org/dendrite"
        VUL_TAG: "v0.9.7"
        GO_VERSION: "1.18"
    container_name: github.com-matrix-org-dendrite-1226-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_conservative/github.com-matrix-org-dendrite-1226-1:/analysis/repo/scan_results"

volumes:
  gopher-shared:
    driver: local
    driver_opts:
      type: none
      device: ${BASE_DIR}/internal/gopher
      o: bind
