version: '3.8'

services:
  id26-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/argoproj/argo-workflows"
        VUL_TAG: "v3.0.10"
        GO_VERSION: "1.15"
    container_name: github.com-argoproj-argo-workflows-26-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-argoproj-argo-workflows-26-1:/analysis/repo/scan_results"
  id39-6:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/argoproj/argo-cd"
        VUL_TAG: "v2.14.4"
        GO_VERSION: "1.22.0"
    container_name: github.com-argoproj-argo-cd-39-6
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-argoproj-argo-cd-39-6:/analysis/repo/scan_results"
  id39-7:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/argoproj/argo-cd"
        VUL_TAG: "v2.14.4"
        GO_VERSION: "1.22.0"
    container_name: github.com-argoproj-argo-cd-39-7
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-argoproj-argo-cd-39-7:/analysis/repo/scan_results"
  id39-8:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/argoproj/argo-cd"
        VUL_TAG: "v2.14.4"
        GO_VERSION: "1.22.0"
    container_name: github.com-argoproj-argo-cd-39-8
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-argoproj-argo-cd-39-8:/analysis/repo/scan_results"
  id63-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/aws/aws-sdk-go"
        VUL_TAG: "v1.32.13"
        GO_VERSION: "1.11"
    container_name: github.com-aws-aws-sdk-go-63-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-aws-aws-sdk-go-63-1:/analysis/repo/scan_results"
  id65-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/aws/aws-sdk-go"
        VUL_TAG: "v1.34.1"
        GO_VERSION: "1.11"
    container_name: github.com-aws-aws-sdk-go-65-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-aws-aws-sdk-go-65-1:/analysis/repo/scan_results"
  id66-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/aws/aws-sdk-go"
        VUL_TAG: "v1.34.1"
        GO_VERSION: "1.11"
    container_name: github.com-aws-aws-sdk-go-66-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-aws-aws-sdk-go-66-1:/analysis/repo/scan_results"
  id130-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/cloudflare/cfrpki"
        VUL_TAG: "v1.2.2"
        GO_VERSION: "1.12"
    container_name: github.com-cloudflare-cfrpki-130-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-cloudflare-cfrpki-130-1:/analysis/repo/scan_results"
  id188-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/cosmos/ethermint"
        VUL_TAG: "v0.4.0"
        GO_VERSION: "1.15"
    container_name: github.com-cosmos-ethermint-188-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-cosmos-ethermint-188-1:/analysis/repo/scan_results"
  id202-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/dedis/kyber"
        VUL_TAG: "v3.0.12"
        GO_VERSION: "1.13"
    container_name: github.com-dedis-kyber-202-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-dedis-kyber-202-1:/analysis/repo/scan_results"
  id204-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/dexidp/dex"
        VUL_TAG: "v2.26.0"
        GO_VERSION: "1.15"
    container_name: github.com-dexidp-dex-204-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-dexidp-dex-204-1:/analysis/repo/scan_results"
  id241-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/filecoin-project/lotus"
        VUL_TAG: "v1.4.2-rc1"
        GO_VERSION: "1.15"
    container_name: github.com-filecoin-project-lotus-241-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-filecoin-project-lotus-241-1:/analysis/repo/scan_results"
  id262-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/flyteorg/flyteadmin"
        VUL_TAG: "v1.1.43"
        GO_VERSION: "1.18"
    container_name: github.com-flyteorg-flyteadmin-262-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-flyteorg-flyteadmin-262-1:/analysis/repo/scan_results"
  id264-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/foxcpp/maddy"
        VUL_TAG: "v0.5.3"
        GO_VERSION: "1.15"
    container_name: github.com-foxcpp-maddy-264-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-foxcpp-maddy-264-1:/analysis/repo/scan_results"
  id264-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/foxcpp/maddy"
        VUL_TAG: "v0.5.3"
        GO_VERSION: "1.15"
    container_name: github.com-foxcpp-maddy-264-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-foxcpp-maddy-264-2:/analysis/repo/scan_results"
  id356-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/gopasspw/gopass"
        VUL_TAG: "v1.10.1"
        GO_VERSION: "1.12"
    container_name: github.com-gopasspw-gopass-356-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-gopasspw-gopass-356-1:/analysis/repo/scan_results"
  id435-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/hashicorp/consul"
        VUL_TAG: "v1.7.1"
        GO_VERSION: "1.12"
    container_name: github.com-hashicorp-consul-435-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-hashicorp-consul-435-1:/analysis/repo/scan_results"
  id460-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/hashicorp/nomad"
        VUL_TAG: "v0.10.2-rc1"
        GO_VERSION: "1.11"
    container_name: github.com-hashicorp-nomad-460-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-hashicorp-nomad-460-1:/analysis/repo/scan_results"
  id570-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/rclone/rclone"
        VUL_TAG: "v1.53.2"
        GO_VERSION: "1.14"
    container_name: github.com-rclone-rclone-570-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-rclone-rclone-570-1:/analysis/repo/scan_results"
  id570-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/rclone/rclone"
        VUL_TAG: "v1.53.2"
        GO_VERSION: "1.14"
    container_name: github.com-rclone-rclone-570-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-rclone-rclone-570-2:/analysis/repo/scan_results"
  id570-3:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/rclone/rclone"
        VUL_TAG: "v1.53.2"
        GO_VERSION: "1.14"
    container_name: github.com-rclone-rclone-570-3
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-rclone-rclone-570-3:/analysis/repo/scan_results"
  id570-4:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/rclone/rclone"
        VUL_TAG: "v1.53.2"
        GO_VERSION: "1.14"
    container_name: github.com-rclone-rclone-570-4
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-rclone-rclone-570-4:/analysis/repo/scan_results"
  id593-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/edgexfoundry/app-functions-sdk-go"
        VUL_TAG: "v2.0.1"
        GO_VERSION: "1.16"
    container_name: github.com-edgexfoundry-app-functions-sdk-go-593-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-edgexfoundry-app-functions-sdk-go-593-2:/analysis/repo/scan_results"
  id593-3:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/edgexfoundry/app-functions-sdk-go"
        VUL_TAG: "v2.0.1"
        GO_VERSION: "1.16"
    container_name: github.com-edgexfoundry-app-functions-sdk-go-593-3
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-edgexfoundry-app-functions-sdk-go-593-3:/analysis/repo/scan_results"
  id617-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/kiali/kiali"
        VUL_TAG: "v1.15.2"
        GO_VERSION: "1.11"
    container_name: github.com-kiali-kiali-617-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-kiali-kiali-617-1:/analysis/repo/scan_results"
  id617-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/kiali/kiali"
        VUL_TAG: "v1.15.2"
        GO_VERSION: "1.11"
    container_name: github.com-kiali-kiali-617-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-kiali-kiali-617-2:/analysis/repo/scan_results"
  id618-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/kiali/kiali"
        VUL_TAG: "v1.15.2"
        GO_VERSION: "1.11"
    container_name: github.com-kiali-kiali-618-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-kiali-kiali-618-1:/analysis/repo/scan_results"
  id618-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/kiali/kiali"
        VUL_TAG: "v1.15.2"
        GO_VERSION: "1.11"
    container_name: github.com-kiali-kiali-618-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-kiali-kiali-618-2:/analysis/repo/scan_results"
  id649-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/kubernetes/kops"
        VUL_TAG: "v1.17.2"
        GO_VERSION: "1.13"
    container_name: github.com-kubernetes-kops-649-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-kubernetes-kops-649-1:/analysis/repo/scan_results"
  id672-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/mellium/xmpp"
        VUL_TAG: "v0.21.0"
        GO_VERSION: "1.16"
    container_name: github.com-mellium-xmpp-672-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-mellium-xmpp-672-1:/analysis/repo/scan_results"
  id680-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/miekg/dns"
        VUL_TAG: "v1.1.24"
        GO_VERSION: "1.12"
    container_name: github.com-miekg-dns-680-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-miekg-dns-680-1:/analysis/repo/scan_results"
  id761-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/pion/dtls"
        VUL_TAG: "v2.1.4"
        GO_VERSION: "1.13"
    container_name: github.com-pion-dtls-761-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-pion-dtls-761-1:/analysis/repo/scan_results"
  id830-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/tendermint/tendermint"
        VUL_TAG: "v0.34.8"
        GO_VERSION: "1.15"
    container_name: github.com-tendermint-tendermint-830-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-tendermint-tendermint-830-1:/analysis/repo/scan_results"
  id830-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/tendermint/tendermint"
        VUL_TAG: "v0.34.8"
        GO_VERSION: "1.15"
    container_name: github.com-tendermint-tendermint-830-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-tendermint-tendermint-830-2:/analysis/repo/scan_results"
  id870-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/weaveworks/weave-gitops"
        VUL_TAG: "v0.11.0-rc.1"
        GO_VERSION: "1.18"
    container_name: github.com-weaveworks-weave-gitops-870-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-weaveworks-weave-gitops-870-1:/analysis/repo/scan_results"
  id870-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/weaveworks/weave-gitops"
        VUL_TAG: "v0.11.0-rc.1"
        GO_VERSION: "1.18"
    container_name: github.com-weaveworks-weave-gitops-870-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-weaveworks-weave-gitops-870-2:/analysis/repo/scan_results"
  id870-3:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/weaveworks/weave-gitops"
        VUL_TAG: "v0.11.0-rc.1"
        GO_VERSION: "1.18"
    container_name: github.com-weaveworks-weave-gitops-870-3
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-weaveworks-weave-gitops-870-3:/analysis/repo/scan_results"
  id870-4:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/weaveworks/weave-gitops"
        VUL_TAG: "v0.11.0-rc.1"
        GO_VERSION: "1.18"
    container_name: github.com-weaveworks-weave-gitops-870-4
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-weaveworks-weave-gitops-870-4:/analysis/repo/scan_results"
  id980-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/docker/docker"
        VUL_TAG: "v28.0.1"
        GO_VERSION: "1.11"
    container_name: github.com-docker-docker-980-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-docker-docker-980-1:/analysis/repo/scan_results"
  id994-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/moby/moby"
        VUL_TAG: "v28.0.1"
        GO_VERSION: "1.11"
    container_name: github.com-moby-moby-994-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-moby-moby-994-1:/analysis/repo/scan_results"
  id1023-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/px-org/PanIndex"
        VUL_TAG: "v3.1.2"
        GO_VERSION: "1.19"
    container_name: github.com-px-org-PanIndex-1023-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-px-org-PanIndex-1023-1:/analysis/repo/scan_results"
  id1098-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/hashicorp/boundary"
        VUL_TAG: "v0.11.2"
        GO_VERSION: "1.19"
    container_name: github.com-hashicorp-boundary-1098-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-hashicorp-boundary-1098-1:/analysis/repo/scan_results"
  id1157-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/traefik/traefik"
        VUL_TAG: "v2.9.5"
        GO_VERSION: "1.19"
    container_name: github.com-traefik-traefik-1157-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-traefik-traefik-1157-1:/analysis/repo/scan_results"
  id1157-2:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/traefik/traefik"
        VUL_TAG: "v2.9.5"
        GO_VERSION: "1.19"
    container_name: github.com-traefik-traefik-1157-2
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-traefik-traefik-1157-2:/analysis/repo/scan_results"
  id1157-3:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/traefik/traefik"
        VUL_TAG: "v2.9.5"
        GO_VERSION: "1.19"
    container_name: github.com-traefik-traefik-1157-3
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-traefik-traefik-1157-3:/analysis/repo/scan_results"
  id1157-4:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/traefik/traefik"
        VUL_TAG: "v2.9.5"
        GO_VERSION: "1.19"
    container_name: github.com-traefik-traefik-1157-4
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-traefik-traefik-1157-4:/analysis/repo/scan_results"
  id1181-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/Masterminds/goutils"
        VUL_TAG: "v1.1.0"
        GO_VERSION: "1.11"
    container_name: github.com-Masterminds-goutils-1181-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-Masterminds-goutils-1181-1:/analysis/repo/scan_results"
  id1182-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/Masterminds/goutils"
        VUL_TAG: "v1.1.0"
        GO_VERSION: "1.11"
    container_name: github.com-Masterminds-goutils-1182-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-Masterminds-goutils-1182-1:/analysis/repo/scan_results"
  id1200-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/cheqd/cheqd-node"
        VUL_TAG: "0.6.8"
        GO_VERSION: "1.17"
    container_name: github.com-cheqd-cheqd-node-1200-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-cheqd-cheqd-node-1200-1:/analysis/repo/scan_results"
  id1207-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/sylabs/sif"
        VUL_TAG: "v2.8.0"
        GO_VERSION: "1.18"
    container_name: github.com-sylabs-sif-1207-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-sylabs-sif-1207-1:/analysis/repo/scan_results"
  id1222-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/sigstore/cosign"
        VUL_TAG: "v1.11.1"
        GO_VERSION: "1.18"
    container_name: github.com-sigstore-cosign-1222-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-sigstore-cosign-1222-1:/analysis/repo/scan_results"
  id1223-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/sigstore/cosign"
        VUL_TAG: "v1.10.0-rc.1"
        GO_VERSION: "1.18"
    container_name: github.com-sigstore-cosign-1223-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-sigstore-cosign-1223-1:/analysis/repo/scan_results"
  id1224-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/sigstore/cosign"
        VUL_TAG: "v1.5.1"
        GO_VERSION: "1.16"
    container_name: github.com-sigstore-cosign-1224-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-sigstore-cosign-1224-1:/analysis/repo/scan_results"
  id1226-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/matrix-org/dendrite"
        VUL_TAG: "v0.9.7"
        GO_VERSION: "1.18"
    container_name: github.com-matrix-org-dendrite-1226-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-matrix-org-dendrite-1226-1:/analysis/repo/scan_results"
  id1242-1:
    build:
      context: .
      args:
        REPO_URL: "https://github.com/sigstore/policy-controller"
        VUL_TAG: "v0.2.0-rc.1"
        GO_VERSION: "1.17"
    container_name: github.com-sigstore-policy-controller-1242-1
    volumes:
      - gopher-shared:/analysis/gopher
      - "${BASE_DIR}/data/analysis/cve/vulnerabilties_liberal/github.com-sigstore-policy-controller-1242-1:/analysis/repo/scan_results"

volumes:
  gopher-shared:
    driver: local
    driver_opts:
      type: none
      device: ${BASE_DIR}/gopher
      o: bind
